"""
Tests day 8 solver.
"""

from test.base_test import BaseTests

from advent_of_code_2024.day_08 import Solver


class TestDay8(BaseTests):
    """Tests the day 8 solver."""

    solver = Solver()
    example_input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
    part_1_solution = 14
    part_2_solution = 34
